# FTNR REPEAT ANALYSIS

# Branch and Agent wise analysis

In [9]:
import pandas as pd  

file_path = "C:\\Users\\Akash\\Desktop\\FTNR-PROJECT\\Nov'24-FTNR_DA_Project\\FTNR Analysis_2024.xlsx"  
data = pd.read_excel(file_path)

def determine_ftnr_status(row):
    # If it's the first attempt and DDE Status is "Approved," it's FTR
    if row['Attempt'] == 1 and row['DDE_Status'] == "Approved":
        return "FTR"
    # If Previous Query is blank, mark as "GOOD FTNR"
    elif pd.isna(row['Previous Query']):
        return "GOOD FTNR"
    # If Previous Query matches the current Query, mark as "GOOD FTNR"
    elif row['Previous Query'] == row['Query']:
        return "GOOD FTNR"
    # Otherwise, it's "BAD FTNR"
    else:
        return "BAD FTNR"

data['FTNR Status (FINAL)'] = data.apply(determine_ftnr_status, axis=1)

agent_group = data.groupby('userid')['FTNR Status (FINAL)'].value_counts(normalize=True).unstack(fill_value=0)
agent_group = agent_group * 100  
agent_group = agent_group.reset_index()  

agent_group.rename(columns={
    "GOOD FTNR": "Good FTNR %",
    "BAD FTNR": "Bad FTNR %",
    "FTR": "FTR %"
}, inplace=True)


branch_group = data.groupby('Branch')['FTNR Status'].value_counts(normalize=True).unstack(fill_value=0)
branch_group = branch_group * 100  
branch_group = branch_group.reset_index()  

branch_group.rename(columns={
    "GOOD FTNR": "Good FTNR %",
    "BAD FTNR": "Bad FTNR %",
    "FTR": "FTR %"
}, inplace=True)


output_file = "C:\\Users\\Akash\\Desktop\\FTNR-PROJECT\\Nov'24-FTNR_DA_Project\\FTNR Analysis_2024.xlsx"  
with pd.ExcelWriter(output_file) as writer:
    
    data.to_excel(writer, sheet_name="FTNR Status", index=False)
    agent_group.to_excel(writer, sheet_name="Agent Analysis", index=False)

    branch_group.to_excel(writer, sheet_name="Branch Analysis", index=False)

print("The FTNR analysis is complete! Results have been saved to a new Excel file.")

The FTNR analysis is complete! Results have been saved to a new Excel file.

In [15]:
import pandas as pd

file_path = "C:\\Users\\Akash\\Desktop\\FTNR-PROJECT\\Nov'24-FTNR_DA_Project\\FTNR Analysis_2024.xlsx"
data = pd.read_excel(file_path)

def determine_ftnr_status(row):
    # If it's the first attempt and DDE Status is "Approved," it's FTR
    if row['Attempt'] == 1 and row['DDE_Status'] == "Approved":
        return "FTR"
    # If there is no new query, it's GOOD FTNR
    if pd.isna(row['Previous Query']):
        return "GOOD FTNR"
    # If the current query matches the previous query, it's GOOD FTNR
    if row['Query'] == row['Previous Query']:
        return "GOOD FTNR"
    # Otherwise, it's BAD FTNR
    return "BAD FTNR"

data['FTNR Status (FINAL)'] = data.apply(determine_ftnr_status, axis=1)

# Agent-wise FTNR analysis
agent_group = data.groupby('username')['FTNR Status (FINAL)'].value_counts(normalize=True).unstack(fill_value=0) * 100
agent_group.rename(columns={
    "GOOD FTNR": "Good FTNR %",
    "BAD FTNR": "Bad FTNR %",
    "FTR": "FTR %"
}, inplace=True)

# Branch-wise FTNR analysis
branch_group = data.groupby('Branch')['FTNR Status (FINAL)'].value_counts(normalize=True).unstack(fill_value=0) * 100
branch_group.rename(columns={
    "GOOD FTNR": "Good FTNR %",
    "BAD FTNR": "Bad FTNR %",
    "FTR": "FTR %"
}, inplace=True)

# Display FTNR Status Data
print("FTNR Status Analysis:")
display(data)

# Display Agent-Wise Analysis
print("\nAgent-Wise FTNR Analysis:")
display(agent_group)

# Display Branch-Wise Analysis
print("\nBranch-Wise FTNR Analysis:")
display(branch_group)

FTNR Status Analysis:

,LoanId,Branch,State,Zone,DDE_Status,Query,Query_ID,Previous Query,FTNR Status,FTNR Status (FINAL),Create_Date,CREATE DATE,CREATE TIME,userid,username,Attempt,User-FTR%,User-GOOD FTNR%,User-BAD FTNR%
0,AAAG71642335,S0141-SULB-TIRUVANNAMALAI,TAMILNADU,SOUTH,Reject,OSV Missing,1,NaN,GOOD FTNR,GOOD FTNR,2024-08-13 13:14:18.243,2024-08-13,13:14:18.243000,394051,T Pavithra,1,0,1.000000,0.000000
1,AAAG71643010,S0138-SULB-PATTUKOTTAI,TAMILNADU,SOUTH,Reject,Aadhar/PAN/Form 60 Missing,2,NaN,GOOD FTNR,GOOD FTNR,2024-07-24 18:16:17.320,2024-07-24,18:16:17.320000,393984,Soundarya R,1,0,0.888889,0.111111
2,AABH92035815,S0080-SULB-SHIVAMOGGA,KARNATAKA,SOUTH,Reject,Bank Statement Incomplete,3,NaN,GOOD FTNR,GOOD FTNR,2024-10-14 14:21:18.370,2024-10-14,14:21:18.370000,393626,Sakthi Balasubramaniyan,3,0,0.600000,0.400000
3,AABH92035815,S0080-SULB-SHIVAMOGGA,KARNATAKA,SOUTH,Reject,Bank Statement Incomplete,3,Bank Statement Incomplete,GOOD FTNR,GOOD FTNR,2024-10-16 16:12:57.090,2024-10-16,16:12:57.090000,397806,Sheik Mujammil,3,0,1.000000,0.000000
4,AABH92035815,S0080-SULB-SHIVAMOGGA,KARNATAKA,SOUTH,Reject,Bank Statement Incomplete,3,Bank Statement Incomplete,GOOD FTNR,GOOD FTNR,2024-10-17 12:19:35.940,2024-10-17,12:19:35.940000,393626,Sakthi Balasubramaniyan,3,0,0.600000,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46319,YYWB92025936,S0241-SULB-HUNSUR,KARNATAKA,SOUTH,Reject,Bank Statement Incomplete,3,NaN,GOOD FTNR,GOOD FTNR,2024-09-06 16:38:40.767,2024-09-06,16:38:40.767000,409872,Gangooli K,1,0,0.000000,0.000000
46320,YYWF71599763,S0074-SULB-SHAMSHABAD,TELANGANA,SOUTH,Reject,Photo of Photocopy uploaded,19,NaN,GOOD FTNR,GOOD FTNR,2024-02-21 04:30:52.427,2024-02-21,04:30:52.427000,401955,Ranjan Choudhury,1,0,1.000000,0.000000
46321,YYWG71601370,S0116-SULB-GWALIOR,MADHYA PRADESH,WEST,Reject,Photo of Electronic Screen not recognizable,6,NaN,GOOD FTNR,GOOD FTNR,2024-03-22 14:45:11.753,2024-03-22,14:45:11.753000,398012,Amarjeet Kumar,1,0,1.000000,0.000000
46322,YYWJ71645955,S0093-SULB-MANDSAUR,MADHYA PRADESH,WEST,Reject,Aadhar/PAN/Form 60 Missing,2,NaN,GOOD FTNR,GOOD FTNR,2024-08-06 17:32:01.410,2024-08-06,17:32:01.410000,393827,bharath S,1,0,0.000000,0.000000
46323,YYXU71607308,S0106-SULB-NASHIK,MAHARASHTRA,WEST,Reject,"Aadhar not Masked by NC, Clear Copy to be Uplo...",9,NaN,GOOD FTNR,GOOD FTNR,2024-03-20 10:43:06.437,2024-03-20,10:43:06.437000,397812,Vishakha Devendra Sutar,1,0,0.800000,0.200000

Agent-Wise FTNR Analysis:

FTNR Status (FINAL)  Bad FTNR %     FTR %  Good FTNR %
username
Abishek               16.735967  0.000000    83.264033
Ajith P A             17.777778  0.000000    82.222222
Ajmala  S M           15.306122  0.000000    84.693878
Akshay                21.879022  0.000000    78.120978
Amarjeet Kumar        12.628866  0.085911    87.285223
...                         ...       ...          ...
saranya S             61.818182  0.000000    38.181818
swathi.v               0.000000  0.000000   100.000000
vijay v               22.352941  0.000000    77.647059
vijayraj              16.666667  0.000000    83.333333
yogeshwaran K         23.703704  0.000000    76.296296

[85 rows x 3 columns]

Branch-Wise FTNR Analysis:

FTNR Status (FINAL)           Bad FTNR %  FTR %  Good FTNR %
Branch
F0192-SULB-JAUNPUR              0.000000    0.0   100.000000
F2763-SULB-JAUNPUR             13.157895    0.0    86.842105
R0001-SULB-RAMANAGARA          13.846154    0.0    86.153846
R0003-SULB-GANGAVATHI          18.181818    0.0    81.818182
R0004-SULB-CHITRADURGA         17.500000    0.0    82.500000
...                                  ...    ...          ...
S0523-SULB-MEDCHAL              5.882353    0.0    94.117647
S0524-SULB-THIRUTHURAIPOONDI   22.222222    0.0    77.777778
S0525-SULB-VIRUDHUNAGAR        28.260870    0.0    71.739130
S0529-SULB-THIRUVARUR          15.625000    0.0    84.375000
TEST BRANCH                     0.000000    0.0   100.000000

[452 rows x 3 columns]